
#include "driver.h"
#include <ntstrsafe.h>


int deviceCount = 0;

WDFDEVICE keyboardInterfaceDevice = NULL;

NTSTATUS DriverEntry(
	_In_ PDRIVER_OBJECT DriverObject,
	_In_ PUNICODE_STRING RegistryPath
)
{
	NTSTATUS status;

	WDFDRIVER hDriver;
	WDF_DRIVER_CONFIG driverConfig;

	WDF_DRIVER_CONFIG_INIT(&driverConfig, EvtDeviceAdd);

	status = WdfDriverCreate(DriverObject, RegistryPath, WDF_NO_OBJECT_ATTRIBUTES, &driverConfig, &hDriver);

	if(!NT_SUCCESS(status))
	{
		DbgPrint("KeyboardMacroDriver failed in DriverEntry");
	}

	keyboardInterfaceDevice = CreateKeyboardInterface(hDriver);

	return status;
}



NTSTATUS EvtDeviceAdd(
	_In_ WDFDRIVER Driver,
	_Inout_ PWDFDEVICE_INIT DeviceInit
)
{
	NTSTATUS status;
	WDFDEVICE hDevice;
	WDF_IO_QUEUE_CONFIG ioQueueConfig;
	PDEVICE_EXTENSION deviceExtension;
	WDF_OBJECT_ATTRIBUTES deviceAttributes;

	UNREFERENCED_PARAMETER(Driver);

	PAGED_CODE();

	//WdfDeviceInitSetCharacteristics(DeviceInit, FILE_AUTOGENERATED_DEVICE_NAME, FALSE);
	//status = WdfDeviceInitAssignSDDLString(DeviceInit, &SDDL_DEVOBJ_SYS_ALL_ADM_RWX_WORLD_R_RES_R);

	WdfFdoInitSetFilter(DeviceInit);

	WdfDeviceInitSetDeviceType(DeviceInit, FILE_DEVICE_KEYBOARD);

	WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_EXTENSION);

	deviceAttributes.EvtDestroyCallback = KeyboardMacroEvtDestroy;

	status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &hDevice);

	if(!NT_SUCCESS(status))
	{
		KdBreakPoint();

		DbgPrint("KeyboardMacroDriver device creation failed");
		return status;
	}

	if (!NT_SUCCESS(status))
	{
		DbgPrint("KeyboardMacroDriver device creation failed");
		return status;
	}

	deviceExtension = GetDeviceExtension(hDevice);
	deviceExtension->OUTPUT_BUFFER = ExAllocatePool2(POOL_FLAG_NON_PAGED, OUTPUT_BUFFER_SIZE_BYTES, 'outb');

	InitializeKeyData(deviceExtension);

	WDF_OBJECT_ATTRIBUTES_INIT(&deviceAttributes);

	WdfSpinLockCreate(&deviceAttributes, &deviceExtension->KeypressSpinLock);

	if(!NT_SUCCESS(status))
	{
		DbgPrint("KeyboardMacroDriver OUTPUT_BUFFER memory allocation failed");
		return status;
	}

	WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&ioQueueConfig, WdfIoQueueDispatchParallel);

	ioQueueConfig.EvtIoInternalDeviceControl = EvtIoDeviceControl;

	status = WdfIoQueueCreate(hDevice, &ioQueueConfig, WDF_NO_OBJECT_ATTRIBUTES, WDF_NO_HANDLE);

	if(!NT_SUCCESS(status))
	{
		DbgPrint("KeyboardMacroDriver IO queue creation failed");
		return status;
	}

	if (keyboardInterfaceDevice != NULL) 
	{
		deviceExtension->KeyboardInterface = keyboardInterfaceDevice;

		PKEYBOARD_CONTEXT keyboardContext = GetKeyboardExtension(keyboardInterfaceDevice);
		keyboardContext->KeyboardDevices[keyboardContext->CurrentDevices++] = hDevice;
	}

	return status;
}

void EvtIoDeviceControl(
	_In_ WDFQUEUE Queue,
	_In_ WDFREQUEST Request,
	_In_ size_t OutputBufferLength,
	_In_ size_t InputBufferLength,
	_In_ ULONG IoControlCode)
{
	WDFDEVICE hDevice;
	PDEVICE_EXTENSION deviceExtension;
	PCONNECT_DATA connectData;
	size_t length;
	NTSTATUS status = STATUS_SUCCESS;

	PINTERNAL_I8042_HOOK_KEYBOARD hookData;

	BOOLEAN forwardWithCompletionRoutine = FALSE;
	WDFCONTEXT completionContext = WDF_NO_CONTEXT;
	WDFMEMORY outputMemory;

	BOOLEAN retValue;

	UNREFERENCED_PARAMETER(OutputBufferLength);
	UNREFERENCED_PARAMETER(InputBufferLength);

	PAGED_CODE();

	hDevice = WdfIoQueueGetDevice(Queue);
	deviceExtension = GetDeviceExtension(hDevice);

	switch (IoControlCode) 
	{
		case IOCTL_INTERNAL_KEYBOARD_CONNECT:
			//Disallow multiple keyboards from being connected to the same port
			if(deviceExtension->KeyboardConnectData.ClassService != NULL)
			{
				status = STATUS_SHARING_VIOLATION;
				break;
			}

			status = WdfRequestRetrieveInputBuffer(Request, sizeof(CONNECT_DATA), &connectData, &length);

			if(!NT_SUCCESS(status))
			{
				break;
			}

			//Save the original connect data before overwriting it
			deviceExtension->KeyboardConnectData = *connectData;

			connectData->ClassDeviceObject = WdfDeviceWdmGetDeviceObject(hDevice);

#pragma warning(disable:4152)
			connectData->ClassService = KeyboardMacroServiceCallback;
#pragma warning(default:4152)

			break;
//		case IOCTL_INTERNAL_KEYBOARD_DISCONNECT:
//			deviceExtension->KeyboardConnectData.ClassDeviceObject = NULL;
//			deviceExtension->KeyboardConnectData.ClassService = NULL;
//			break;
		case IOCTL_INTERNAL_I8042_HOOK_KEYBOARD:
			status = WdfRequestRetrieveInputBuffer(Request, sizeof(INTERNAL_I8042_HOOK_KEYBOARD), &hookData, &length);
			
			if(!NT_SUCCESS(status))
			{
				break;
			}

			//Grab the hook's current context and replace it with our device extension
			deviceExtension->UpperContext = hookData->Context;
			hookData->Context = (PVOID)deviceExtension;

			if(hookData->InitializationRoutine)
			{
				deviceExtension->UpperInitializationRoutine = hookData->InitializationRoutine;
			}

			hookData->InitializationRoutine = KeyboardMacro_InitializationRoutine;

			if (hookData->IsrRoutine) 
			{
				deviceExtension->UpperIsrHook = hookData->IsrRoutine;
			}

			hookData->IsrRoutine = (PI8042_KEYBOARD_ISR)KeyboardMacro_IsrHook;
			break;
		case IOCTL_KEYBOARD_QUERY_ATTRIBUTES:
			forwardWithCompletionRoutine = TRUE;
			completionContext = deviceExtension;
			break;
	}

	if(!NT_SUCCESS(status))
	{
		WdfRequestComplete(Request, status);
		return;
	}

	if (forwardWithCompletionRoutine) 
	{
		status = WdfRequestRetrieveOutputMemory(Request, &outputMemory);

		if(!NT_SUCCESS(status))
		{
			WdfRequestComplete(Request, status);
			return;
		}

		status = WdfIoTargetFormatRequestForInternalIoctl(
			WdfDeviceGetIoTarget(hDevice),
			Request,
			IoControlCode,
			NULL,
			NULL,
			outputMemory,
			NULL);

		if (!NT_SUCCESS(status))
		{
			WdfRequestComplete(Request, status);
			return;
		}

		WdfRequestSetCompletionRoutine(Request, KeyboardMacroRequestCompletionRoutine, completionContext);

		retValue = WdfRequestSend(Request, WdfDeviceGetIoTarget(hDevice), WDF_NO_SEND_OPTIONS);

		if (retValue == FALSE) 
		{
			status = WdfRequestGetStatus(Request);
			WdfRequestComplete(Request, status);
		}
	}
	else 
	{
		KeyboardMacroDispatchPassThrough(Request, WdfDeviceGetIoTarget(hDevice));
	}
}

VOID KeyboardMacroServiceCallback(
	IN PDEVICE_OBJECT DeviceObject,
	IN PKEYBOARD_INPUT_DATA InputDataStart,
	IN PKEYBOARD_INPUT_DATA InputDataEnd,
	IN OUT PULONG InputDataConsumed
)
{
	PDEVICE_EXTENSION deviceExtension;
	WDFDEVICE hDevice;

	hDevice = WdfWdmDeviceGetWdfDeviceHandle(DeviceObject);

	deviceExtension = GetDeviceExtension(hDevice);
	
	KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL,"Service callback: %hu", InputDataStart->MakeCode));

	WdfSpinLockAcquire(deviceExtension->KeypressSpinLock);
	for(PKEYBOARD_INPUT_DATA i = InputDataStart; i < InputDataEnd; i++)
	{
		//ignore fake shifts
		if (i->MakeCode == 0x2a && i->Flags & KEY_E0)
		{
			continue;
		}

		if(deviceExtension->KEY_MAP[i->MakeCode] != MACRO_KEY_INVALID)
		{
			//If this is a key up event, ensure there was a registered key down event beforehand
			if((i->Flags & KEY_BREAK) && deviceExtension->KEY_MAP[i->MakeCode] == 1)
			{
				deviceExtension->KEYS_DOWN--;
				deviceExtension->KEY_MAP[i->MakeCode] = 0;
			}
			else if(!(i->Flags & KEY_BREAK))
			{
				//Check if this is a repeat key
				if (deviceExtension->KEY_MAP[i->MakeCode] == 0)
				{
					deviceExtension->KEYS_DOWN++;
					deviceExtension->KEY_MAP[i->MakeCode] = 1;

					if (deviceExtension->OutputBufferLength < OUTPUT_BUFFER_SIZE)
					{
						memcpy((OUTPUT_BUFFER_STRUCT*)deviceExtension->OUTPUT_BUFFER + deviceExtension->OutputBufferLength, i, sizeof(OUTPUT_BUFFER_STRUCT));

						deviceExtension->OutputBufferLength++;
					}
					else
					{
						InitializeKeyData(deviceExtension);
					}
				}
			}
		}
		else
		{
			switch(i->MakeCode)
			{
				//If the keyboard throws an error or the escape key is pressed then reset the key data
				case 0xff:
				case 0x01:
					InitializeKeyData(deviceExtension);
					break;
			}
		}
	}

	if (deviceExtension->IsRegistered == TRUE)
	{
		KEYBOARD_INPUT_DATA replacementBuffer[2];

		replacementBuffer[0].Reserved = 0;
		replacementBuffer[0].MakeCode = 0xFF;

		replacementBuffer[1] = *InputDataEnd;

		InputDataStart = replacementBuffer;
		InputDataEnd = replacementBuffer + 1;
		*InputDataConsumed = 0;
	}

	if (deviceExtension->KEYS_DOWN == 0 && deviceExtension->OutputBufferLength > 0)
	{
		if (deviceExtension->UserAppCallbackRequest != NULL)
		{
			//If we have a pending callback, use it
			WdfRequestCompleteWithInformation(deviceExtension->UserAppCallbackRequest, STATUS_SUCCESS, MACRO_RESPONSE_KEY_DATA_AVAILABLE);
			deviceExtension->UserAppCallbackRequest = NULL;
		}
		else if(deviceExtension->OutputBufferLength == 3)
		{
			const int SCAN_CODE_LENGTH = 3;
			//right ctrl + page up + page down
			int activationScanCodes[3];

			activationScanCodes[0] = 0x1d;
			activationScanCodes[1] = 0x49;
			activationScanCodes[2] = 0x51;

			int unitID = -1;

			OUTPUT_BUFFER_STRUCT keyData;

			int i;
			for (i = 0; i < (int)deviceExtension->OutputBufferLength; i++) 
			{
				keyData = *((OUTPUT_BUFFER_STRUCT*)deviceExtension->OUTPUT_BUFFER + i);

				//ensure all of the keypresses come from the same keyboard
				if (unitID == -1)
				{
					unitID = keyData.UnitId;
				}
				else if (unitID != keyData.UnitId)
				{
					goto clearBuffer;
				}

				//check the activation sequence
				int j;
				for (j = 0; j < SCAN_CODE_LENGTH; j++)
				{
					if(activationScanCodes[j] == keyData.MakeCode)
					{
						activationScanCodes[j] = -1;
						break;
					}

					switch(keyData.MakeCode)
					{
						case 0x49:
						case 0x51:
							//The e0 flag indicates that these page up and page down codes
							//are from the dedicated buttons as opposed to the numpad
							if (!(keyData.Flags & KEY_E0)) 
								goto clearBuffer;
							break;
					}
				}

				if (j == SCAN_CODE_LENGTH)
					goto clearBuffer;
			}

			for (i = 0; i < SCAN_CODE_LENGTH; i++) 
			{
				if (activationScanCodes[i] != -1)
					goto clearBuffer;
			}

			//register the keyboard
			KeyboardInterfaceRegisterDevice(deviceExtension->KeyboardInterface, hDevice);
		}
		else
		{
			clearBuffer:
			//Otherwise clear the buffer and await a user app callback
			deviceExtension->OutputBufferLength = 0;
		}
	}

	WdfSpinLockRelease(deviceExtension->KeypressSpinLock);
	

	//This calls the original connect data's callback
	(*(PSERVICE_CALLBACK_ROUTINE)deviceExtension->KeyboardConnectData.ClassService)(
		deviceExtension->KeyboardConnectData.ClassDeviceObject,
		InputDataStart,
		InputDataEnd,
		InputDataConsumed
		);
}

VOID KeyboardMacroDispatchPassThrough(
	_In_ WDFREQUEST Request,
	_In_ WDFIOTARGET Target
)
{
	WDF_REQUEST_SEND_OPTIONS options;
	NTSTATUS status = STATUS_SUCCESS;
	BOOLEAN completed;

	WDF_REQUEST_SEND_OPTIONS_INIT(&options, WDF_REQUEST_SEND_OPTION_SEND_AND_FORGET);

	completed = WdfRequestSend(Request, Target, &options);

	if (completed == FALSE) 
	{
		status = WdfRequestGetStatus(Request);
		DbgPrint("KeyboardMacroDriver dispatch pass through failed");
		WdfRequestComplete(Request, status);
	}
}
#pragma region PS/2 functions
BOOLEAN KeyboardMacro_IsrHook(
	PVOID                  IsrContext,
	PKEYBOARD_INPUT_DATA   CurrentInput,
	POUTPUT_PACKET         CurrentOutput,
	UCHAR                  StatusByte,
	PUCHAR                 DataByte,
	PBOOLEAN               ContinueProcessing,
	PKEYBOARD_SCAN_STATE   ScanState
)
{
	PDEVICE_EXTENSION deviceExtension;
	BOOLEAN returnValue = TRUE;

	//KdBreakPoint();

	deviceExtension = (PDEVICE_EXTENSION)IsrContext;

	if (deviceExtension->UpperIsrHook) 
	{
		returnValue = (*deviceExtension->UpperIsrHook)(
			deviceExtension->UpperContext,
			CurrentInput,
			CurrentOutput,
			StatusByte,
			DataByte,
			ContinueProcessing,
			ScanState
			);

		if (!returnValue || !(*ContinueProcessing)) 
		{
			return returnValue;
		}
	}

	*ContinueProcessing = TRUE;
	return returnValue;
}

NTSTATUS KeyboardMacro_InitializationRoutine(
	IN PVOID                           InitializationContext,
	IN PVOID                           SynchFuncContext,
	IN PI8042_SYNCH_READ_PORT          ReadPort,
	IN PI8042_SYNCH_WRITE_PORT         WritePort,
	OUT PBOOLEAN                       TurnTranslationOn
) 
{
	PDEVICE_EXTENSION deviceExtension;
	NTSTATUS status = STATUS_SUCCESS;

	//KdBreakPoint();

	deviceExtension = (PDEVICE_EXTENSION)InitializationContext;

	if(deviceExtension->UpperInitializationRoutine)
	{
		status = (*deviceExtension->UpperInitializationRoutine)(
			deviceExtension->UpperContext,
			SynchFuncContext,
			ReadPort,
			WritePort,
			TurnTranslationOn
			);

		if(!NT_SUCCESS(status))
		{
			return status;
		}
	}

	*TurnTranslationOn = TRUE;
	return status;
}

VOID KeyboardMacroRequestCompletionRoutine(
	WDFREQUEST                  Request,
	WDFIOTARGET                 Target,
	PWDF_REQUEST_COMPLETION_PARAMS CompletionParams,
	WDFCONTEXT                  Context
) 
{
	WDFMEMORY buffer = CompletionParams->Parameters.Ioctl.Output.Buffer;
	NTSTATUS status = CompletionParams->IoStatus.Status;

	UNREFERENCED_PARAMETER(Target);

	//KdBreakPoint();

	if (NT_SUCCESS(status)
		&& CompletionParams->Type == WdfRequestTypeDeviceControlInternal
		&& CompletionParams->Parameters.Ioctl.IoControlCode == IOCTL_KEYBOARD_QUERY_ATTRIBUTES) 
	{
		if (CompletionParams->Parameters.Ioctl.Output.Length >= sizeof(KEYBOARD_ATTRIBUTES))
		{
			status = WdfMemoryCopyToBuffer(buffer,
				CompletionParams->Parameters.Ioctl.Output.Offset,
				&((PDEVICE_EXTENSION)Context)->KeyboardAttributes,
				sizeof(KEYBOARD_ATTRIBUTES));
		}
	}

	WdfRequestComplete(Request, status);
}

#pragma endregion PS/2 functions


VOID KeyboardMacroEvtDestroy(
	_In_ WDFOBJECT Object
)
{
	PDEVICE_EXTENSION deviceExtension = GetDeviceExtension(Object);

	if (deviceExtension->KeyboardInterface != NULL) 
	{
		KeyboardInterfaceRemoveDevice(deviceExtension->KeyboardInterface, Object);
		deviceExtension->KeyboardInterface = NULL;
	}

	if (deviceExtension->OUTPUT_BUFFER != NULL) 
	{
		ExFreePoolWithTag(deviceExtension->OUTPUT_BUFFER, 'outb');
		deviceExtension->OUTPUT_BUFFER = NULL;
	}
}



VOID PrepareKeyMapArray(UCHAR* keyMap) 
{
	RtlZeroMemory(keyMap, KEY_MAP_SIZE);

	keyMap[0x00] = MACRO_KEY_INVALID; //Keyboard error
	keyMap[0xaa] = MACRO_KEY_INVALID; //Basic assurance test (BAT)
	keyMap[0xee] = MACRO_KEY_INVALID; //Result of echo command
	keyMap[0xf1] = MACRO_KEY_INVALID; //Response to a4
	keyMap[0xfa] = MACRO_KEY_INVALID; //Acknowledge from keyboard
	keyMap[0xfc] = MACRO_KEY_INVALID; //BAT error or mouse transmit error
	keyMap[0xfd] = MACRO_KEY_INVALID; //Internal failure
	keyMap[0xfe] = MACRO_KEY_INVALID; //Keyboard fails to ack
	keyMap[0xff] = MACRO_KEY_INVALID; //Keyboard error

	keyMap[0x01] = MACRO_KEY_INVALID; //Escape key, reserved for clearing the key buffer if things break
}

VOID InitializeKeyData(PDEVICE_EXTENSION deviceExtension) 
{
	PrepareKeyMapArray(deviceExtension->KEY_MAP);
	deviceExtension->KEYS_DOWN = 0;
	deviceExtension->OutputBufferLength = 0;
}